version: '3'

services:

  redis:
     image:  redis:latest
     ports:
       - '6379:6379'


  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
    environment:
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672//"
    ports:
      - "8005:8005"
    links:
      - redis

  celery_worker:
    build: .
    command: bash -c "celery -A django_cel_doc worker -l info"
    volumes:
      - .:/django_cel_doc
    links:
      - redis